#!/bin/bash
# Panera Bread wifi hack

magic=`tr -dc A-F0-9 < /dev/urandom | head -c 10 | sed -r 's/(..)/\1:/g;s/:$//;s/^/02:/'`

for (( ; ; ))
do
   sleep 5
   sudo ifconfig wlp3s0 down; sudo ifconfig wlp3s0 hw ether $magic ; sudo ifconfig wlp3s0 up
done
